@startuml
start

:MENU OPERASI;
repeat
  :Input pilihan;
  if (pilihan == 1) then (true)
  :tambah;
    repeat
      :Masukan Angka pertama;
      :Masukan Angka Kedua;
      :Hasil;
    repeat while (pilihan != 1)
  else (false)






@enduml