@startuml

start
:COFFEE & RACE;
repeat
  :Input pilihan;
  if (pilihan == 1) then (true)
    :Display MENU TEH;
    repeat
      :Input qty Teh;
      :Calculate total Teh;
      :Display total Teh;
    repeat while (pilihan != 4)
  else (false)
    if (pilihan == 2) then (true)
      :Display MENU KOPI;
      repeat
        :Calculate total Kopi;
        :Display total Kopi;
      repeat while (pilihan != 4)
  else (false)
    if (pilihan == 3) then (true)
      :Display MENU WEDANG;
      repeat
        :Calculate total Kopi;
        :Display total Kopi;
      repeat while (pilihan != 4)
      else (false)
      :Pilihan Salah;
    endif
  endif
 while(pilihan != 4)

:Exit;
stop

@enduml