@startuml

start

:Display MENU PRISA COFFEE SHOP;
repeat
  :Input pilihan;
  if (pilihan == 1) then (true)
    :Display MENU TEH;
    repeat
      :Input harga Teh;
      :Input qty Teh;
      :Calculate total Teh;
      :Display total Teh;
    repeat while (pilihan != 3)
  else (false)
    if (pilihan == 2) then (true)
      :Display MENU KOPI;
      repeat
        :Input qty Kopi;
        :Calculate total Kopi;
        :Display total Kopi;
      repeat while (pilihan != 3)
    else (false)
      :Pilihan Salah;
    endif
  endif
repeat while (pilihan != 2)

:Exit;
stop

@enduml